package model;

import org.eclipse.jetty.util.security.Credential.MD5;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class InformBase<M extends InformBase<M>> extends Model<M> implements IBean {


}
